version: "3"
services:
  react-app:
    #here we've to specify the location of our Makefile
    build: ./Front-End/
    stdin_open: true
    #here we're mapping the exposed port i.e, 3000 to our machine port 3000.
    # so that we can test the application on our port 3000.
    ports: 
      - "3000:3000"
    networks:
      - mern-app
    volumes:
      - ./Back-End/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - api-server
  api-server:
    #here we've to specify the location of our Makefile
    build: ./Back-End/
    ports:
    #here we're mapping the exposed port i.e, 5000 to our machine port 5000.
    # so that we can test the application on our port 5000.
      - "5000:5000"
    networks:
      - mern-app
    volumes:
      - ./Back-End/:/usr/src/app
      - /usr/src/app/node_modules
 
networks:
  mern-app:
    driver: bridge
